### ISSUE TITLE
Announcing Squashtoberfest winners!

### ISSUE THREAD

**Issue by filmaj** [adobe/squashtoberfest#5]
Hello dearest open source community contributors!

I am tagging you in this issue as, according to our numbers, you have issued 5 pull requests to repos in the Magento GitHub organization or 5 pull requests to repos in the Adobe GitHub organization. With that, you get a t-shirt!

# Instructions

In order for us to send a snazzy t-shirt your way, you will need to e-mail me at `maj@adobe.com` the following information:

1. Your full name
2. Your GitHub.com username
3. Your T-shirt size, in United States sizes (extra small, small, medium, large, extra large, XXL) (we are using USA sizes since we will be ordering them from a supplier based in the USA)
4. Your full shipping address, clearly labeled with as much details as is necessary to successfully complete international shipping, this likely means:
    - Street name and number and apartment/unit, if applicable
    - City
    - State, if applicable
    - Country
    - Zip or postal code, if applicable
5. A phone number for contact purposes in case the shipping/delivery system requires it

Once you have emailed me the above information, **please post a comment in this issue stating that you have emailed me the information**. This is important to ensure that the above shipping information is actually coming from the right person, especially since many of you do not have a public e-mail associated with your github.com username. Once I have confirmed receipt of the required information and you have commented in this issue, I will check off your name in the list below.

# Deadline For Information Submission

Please send this information to me within the next two weeks. Orders for T-shirts will be placed on **Friday, November 29th, 2019**. 

# Winners

Without further ado, the winners! 

## Magento T-Shirt

Winners of a snazzy **Magento T-Shirt** in thanks for contributing five or more pull requests to github.com/magento repos during the month of October:

![11345_Squashtoberfest_Design_r2v2-o](https://user-images.githubusercontent.com/52645/68972505-fd67bd80-07b9-11ea-98bb-43dc1115d6e0.png)

- [x] @drpayyne
- [x] @atwixfirster
- [x] @edenduong
- [x] @eduard13
- [x] @DanielRuf
- [x] @konarshankar07
- [x] @serhiyzhovnir
- [x] @hellotaran
- [x] @andrey-legayev
- [x] @rahulwebkul
- [x] @maheshWebkul721
- [x] @shikhamis11
- [x] @carusogabriel
- [x] @peter279k
- [ ] @sanganinamrata
- [x] @Bartlomiejsz
- [x] @imagentleman
- [x] @hostep
- [x] @korostii
- [x] @rafaelstz
- [ ] @revanth0212
- [x] @krzksz
- [x] @gauravagarwal1001
- [x] @butuzov
- [x] @dani97
- [x] @jonashrem
- [ ] @lfluvisotto
- [x] @vishalverma279
- [x] @torhoehn
- [x] @SebastianKlett
- [x] @cedarvinda

## Adobe T-Shirt

Winners of a snazzy **Adobe T-Shirt** in thanks for contributing five or more pull requests to github.com/adobe repos during the month of October:

<img width="770" alt="11345_Squashtoberfest_Design_r2v2-AC-o" src="https://user-images.githubusercontent.com/52645/68972762-84b53100-07ba-11ea-8842-80d03412012c.png">

- [x] @sidhyatikku
- [x] @flopp
- [x] @medusalix
- [x] @dlemstra
- [x] @pqrth
- [x] @haktober
- [x] @kotisyamala
- [x] @RanadeepPolavarapu
- [x] @wenzdey
- [x] @gahag

# Questions?

If you have any questions or concerns, feel free to e-mail me privately or post here in the comments.

Thanks again for contributing during Squashtoberfest!

**Comment by sidhyatikku** [comment]
Hi @filmaj 
I have emailed you my details.

**Comment by imagentleman** [comment]
@filmaj Just emailed my info.

**Comment by krzksz** [comment]
@filmaj Info sent.

**Comment by Bartlomiejsz** [comment]
Hi @filmaj
Sent you my info

**Comment by atwixfirster** [comment]
Hi @filmaj
I have emailed you my details.

Thanks

**Comment by jonashrem** [comment]
Hi @filmaj 

just send you the mail.

**Comment by edenduong** [comment]
Hi @filmaj,
I have emailed my info. Please check it. Thanks!

**Comment by rafaelstz** [comment]
Hi @filmaj,

I've sent the email.

Thank you.

**Comment by kotisyamala** [comment]
Hay @filmaj I've raised 5 pull requests to the repo **https://github.com/adobe/aem-core-wcm-components** getting the hactoberfest T-shirt but not here any criteria that needs to be met ? so the i'll try for the nextime.

**Comment by mahesh-rajawat** [comment]
@filmaj i have sent the mail

Thanks

**Comment by drpayyne** [comment]
Hey @filmaj, I've sent the mail. Thank you.

**Comment by Bartlomiejsz** [comment]
Hi @filmaj, sent you email yesterday 😊

**Comment by dani97** [comment]
Hi @filmaj. I have sent the mail.
Thanks  :)

**Comment by eduard13** [comment]
Hey @filmaj, I've just sent you the details.
Thanks.

**Comment by carusogabriel** [comment]
@filmaj Details sent 👍

**Comment by torhoehn** [comment]
@filmaj Sent you the information you asked for. :)

**Comment by butuzov** [comment]
@filmaj Done.

**Comment by flopp** [comment]
@filmaj Mail sent. Thanks!

**Comment by serhiyzhovnir** [comment]
@filmaj 
I've just sent the mail.
Thank you!

**Comment by medusalix** [comment]
@filmaj Mail sent. Thank you 😃.

**Comment by DanielRuf** [comment]
@filmaj I have sent you an email with the requested information.
Thank you!

**Comment by hellotaran** [comment]
Email sent.

**Comment by SebastianKlett** [comment]
@filmaj Mail sent.  Thanks !

**Comment by peter279k** [comment]
Hi @filmaj, I've sent you the shipping information.

Thanks :)!

**Comment by ghost** [comment]
@filmaj - I've sent you my details.

Thanks

**Comment by dlemstra** [comment]
Just mailed you @filmaj.

**Comment by filmaj** [comment]
Alright, through the weekend I received information from 22 of 35 people! Great progress. Hopefully we can get the final 13 contestant winner details soon so we can send in the orders to make the shirts and then finally ship them all out to you all.

Thanks for your patience during this process 🙏

**Comment by haktober** [comment]
hi @filmaj , e-mailed. thanks!

**Comment by filmaj** [comment]
@kotisyamala sorry about that, I am not sure why you didn't show up in my github search API results. I've added you to the list. Please email me the info as per the original post.

**Comment by kotisyamala** [comment]
:) Thanks @filmaj I've sent my details.

**Comment by shikhamis11** [comment]
@filmaj
I've just sent the mail.
Thank you!

**Comment by distributedlock** [comment]
Hi @filmaj, I have contributed 5 PRs (all successfully merged) to a combination of Adobe and Magento repos. I thought this would quality under Hacktoberfest for the T-shirt as the wording mentioned *"5 pull requests to either github.com/magento or github.com/adobe repositories"* [[1]](https://community.magento.com/t5/Magento-DevBlog/Squashtoberfest-2019/ba-p/143694) [[2]](https://opensource.adobe.com/squashtoberfest/). Could you please check if this qualifies for the T-shirt? If not, it's totally fine. I will participate and try again next year. 

Here are my merged PRs:
1. https://github.com/magento/pwa-studio/pull/1853
2. https://github.com/magento/pwa-studio/pull/1854
3. https://github.com/adobe/helix-static/pull/74
4. https://github.com/adobe/helix-cli/pull/1168
5. https://github.com/adobe/helix-cli/pull/1170

Thanks a lot to Adobe & Magento for participating in Hacktoberfest by the way, it was a great experience. 😄

**Comment by wenzdey** [comment]
@filmaj
Hello, could you review my PRs? I believe I fit the requirements of five PRs to Adobe. Thank you for encouraging us to participate.

https://github.com/adobe/brackets/pull/14874
https://github.com/adobe/avmplus/pull/7
https://github.com/adobe/aep-sdks-documentation/pull/1
https://github.com/adobe/ops-cli/pull/70
https://github.com/adobe/spectrum-css/pull/307

**Comment by korostii** [comment]
Hi @filmaj
I have just emailed you my info.

**Comment by filmaj** [comment]
@RanadeepPolavarapu my query involved ensuring there were 5 PRs to either org individually, which I think was why it didn't catch you, but I'll put you on the list for an Adobe T-shirt. Please email me info as per above.

@wenzdey added you to the Adobe list as well. Please e-mail me the info as per above.

**Comment by gahag** [comment]
@filmaj I've also contributed 5 pull requests:
https://github.com/adobe/ops-cli/pull/75
https://github.com/adobe/sbmc/pull/11
https://github.com/adobe/ride/pull/53
https://github.com/adobe/aem-core-wcm-components/pull/797
https://github.com/adobe/sbmc/pull/12
Do I qualify for the rewards?

**Comment by filmaj** [comment]
Yes @gahag i will add you to the list.

**Comment by gahag** [comment]
@filmaj details sent (subject: Squashtoberfest rewards (gahag)). Thanks!

**Comment by distributedlock** [comment]
@filmaj I have sent you my details. Thanks 😃.

**Comment by wenzdey** [comment]
@filmaj I have sent info.

**Comment by konarshankar07** [comment]
Hello @filmaj ,
I have sent an email.
Thanks

**Comment by cedarvinda** [comment]
Hi @filmaj , I have contributed 5 PRs (all successfully merged) to Magento repos. But my name is missing in list.
Here are my merged PRs:

1. https://github.com/magento/magento2/pull/25241
2. https://github.com/magento/magento2/pull/25208
3. https://github.com/magento/magento2/pull/25203
4. https://github.com/magento/magento2/pull/25087
5. https://github.com/magento/magento2/pull/25368

Please check these are my PR's.

**Comment by ghost** [comment]
@filmaj i have sent the mail

Thanks

**Comment by ghost** [comment]
Hi @filmaj , I have contributed more than 5 PRs to Magento repos. But my name is missing in list.
Here are my PRs:

https://github.com/magento/magento2/pull/25239
https://github.com/magento/magento2/pull/25047
https://github.com/magento/magento2/pull/25215
https://github.com/magento/magento2/pull/25089
https://github.com/magento/magento2/pull/25062
https://github.com/magento/magento2/pull/25011
https://github.com/magento/magento2/pull/25000

Please check these are my PR's.

**Comment by Shubham0492** [comment]
Hi @filmaj , I have contributed more than 5 PRs to Magento repos. But my name is missing in list. Please let me know the reason.
Here are my  PRs:

https://github.com/magento/magento2/pull/25200
https://github.com/magento/magento2/pull/25377
https://github.com/magento/magento2/pull/25225
https://github.com/magento/magento2/pull/25256
https://github.com/magento/magento2/pull/25019
https://github.com/magento/magento2/pull/24914


Please check these are my PR's.

**Comment by filmaj** [comment]
@cedarvinda I have reviewed your PRs and added you to the list. Please e-mail me the requested info.

@vishesh-webkul @Shubham-Webkul after reviewing your PRs, unfortunately they do not qualify. Several were closed as invalid or duplicates and several are still open and inactive. While we appreciate all contributions, we also want to encourage high quality contributions in the spirit of improving the project.

**Comment by andrey-legayev** [comment]
Hi @filmaj, I've sent you my details.

**Comment by cedarvinda** [comment]
@filmaj 
I've just sent the mail.
Thank you!

**Comment by filmaj** [comment]
We are just missing details from four people in order to move forward!

@lfluvisotto, @revanth0212, @hostep, @sanganinamrata please take a look at the information I need in the original post of this issue so I can make sure to send you a T-shirt!

**Comment by tacoelho** [comment]
Hi @filmaj 
I fit the requirements but my name is not on the list. Could you check, please? Thanks:

[1](https://github.com/adobe/spectrum-css/pull/309)
[2](https://github.com/adobe/spectrum-css/pull/313)
[3](https://github.com/adobe/ride/pull/50)
[4](https://github.com/adobe/starter-repo/pull/14)
[5](https://github.com/adobe/helix-markdown-preview/pull/65)

**Comment by vpondala** [comment]
@filmaj I submitted 2 PRs, wondering if you can make an exception and send me a tee too..

**Comment by fluffybird2323** [comment]
I too made 5 PRs please see :
https://github.com/adobe/hyde/pull/43
https://github.com/adobe/NLP-Cube/pull/106
https://github.com/adobe/open-development-template/pull/2
https://github.com/adobe/squashtoberfest/pull/2
https://github.com/Adobe-Marketing-Cloud/aep-sdks-documentation/pull/161

**Comment by DanielRuf** [comment]
> [fluffybird2323](/fluffybird2323)

High quality PRs are needed.
https://opensource.adobe.com/squashtoberfest/

> Please note that these pull requests should be of high quality! Adding punctuation, rewriting sentences in documentation, or other such similar patches that do not provide added value to the project will not be counted! It is always best to tackle open issues in the project instead of sending a pull request without first having a conversation about a changeset with the project maintainers.

https://github.com/adobe/squashtoberfest/issues/5#issuecomment-556011900

This also applies to you.

> @vishesh-webkul @Shubham-Webkul after reviewing your PRs, unfortunately they do not qualify. Several were closed as invalid or duplicates and several are still open and inactive. While we appreciate all contributions, we also want to encourage high quality contributions in the spirit of improving the project.

**Comment by DanielRuf** [comment]
@fluffybird2323

High quality PRs are needed.
https://opensource.adobe.com/squashtoberfest/

> Please note that these pull requests should be of high quality! Adding punctuation, rewriting sentences in documentation, or other such similar patches that do not provide added value to the project will not be counted! It is always best to tackle open issues in the project instead of sending a pull request without first having a conversation about a changeset with the project maintainers.

https://github.com/adobe/squashtoberfest/issues/5#issuecomment-556011900

This also applies to you.

> @vishesh-webkul @Shubham-Webkul after reviewing your PRs, unfortunately they do not qualify. Several were closed as invalid or duplicates and several are still open and inactive. While we appreciate all contributions, we also want to encourage high quality contributions in the spirit of improving the project.

**Comment by DanielRuf** [comment]
@fluffybird2323 @tacoelho

High quality PRs are needed.
https://opensource.adobe.com/squashtoberfest/

> Please note that these pull requests should be of high quality! Adding punctuation, rewriting sentences in documentation, or other such similar patches that do not provide added value to the project will not be counted! It is always best to tackle open issues in the project instead of sending a pull request without first having a conversation about a changeset with the project maintainers.

https://github.com/adobe/squashtoberfest/issues/5#issuecomment-556011900

This also applies to you.

> @vishesh-webkul @Shubham-Webkul after reviewing your PRs, unfortunately they do not qualify. Several were closed as invalid or duplicates and several are still open and inactive. While we appreciate all contributions, we also want to encourage high quality contributions in the spirit of improving the project.

**Comment by silvia-odwyer** [comment]
Hi there,
I'm just wondering if I qualify; I submitted the following 5 PRs over the month of October, which were merged successfully. @filmaj 

1. https://github.com/adobe/helix-static/pull/95
2. https://github.com/adobe/adobe-fetch/pull/21
3. https://github.com/adobe/helix-log/pull/56
4. https://github.com/adobe/helix-logging/pull/104
5. https://github.com/adobe/helix-word2md/pull/15

Thanks! ^^

**Comment by DanielRuf** [comment]
@silvia-odwyer 

> Adding punctuation, rewriting sentences in documentation, or other such similar patches that do not provide added value to the project will not be counted!

**Comment by hostep** [comment]
@filmaj: just send you my information, sorry for delay, I was away in holiday for the past 2 weeks 🌴

**Comment by tacoelho** [comment]
> @fluffybird2323 @tacoelho
> 
> High quality PRs are needed.
> https://opensource.adobe.com/squashtoberfest/
> 
> > Please note that these pull requests should be of high quality! Adding punctuation, rewriting sentences in documentation, or other such similar patches that do not provide added value to the project will not be counted! It is always best to tackle open issues in the project instead of sending a pull request without first having a conversation about a changeset with the project maintainers.
> 
> [#5 (comment)](https://github.com/adobe/squashtoberfest/issues/5#issuecomment-556011900)
> 
> This also applies to you.
> 
> > @vishesh-webkul @Shubham-Webkul after reviewing your PRs, unfortunately they do not qualify. Several were closed as invalid or duplicates and several are still open and inactive. While we appreciate all contributions, we also want to encourage high quality contributions in the spirit of improving the project.

I didn´t notice that, just wanted to help anyway. A billion dollar company giving cotton for high quality PRs won´t be worth of my time anymore.

**Comment by drpayyne** [comment]
Hey @filmaj. Any update on this? Thanks!

**Comment by filmaj** [comment]
The update is: we've put the T-shirt order in.

**Comment by lfluvisotto** [comment]
Hi @filmaj,

I sent an email message to you.

Thank you.

**Comment by sanganinamrata** [comment]
@filmaj Hi,

Sorry for the late reply...
I've sent you an email containing my contact details.

Thank you.

**Comment by filmaj** [comment]
Hey all, sorry for the silence on my end, was on time off for most of December.

The t-shirt order was sent mid-December, so I think some, if not most, of you should have t-shirts in hand. We'd love to see them if you want to share pics of you rocking them (if you do so on twitter, make sure to tag our `@MagentoEngCom` twitter account@)!

Thanks for all the contributions and enjoy the threads!

**Comment by gahag** [comment]
@filmaj Can we by any chance get a tracking code for the shipment? I live in Brazil, and sometimes things get lost in the way around here, so it's always good to keep an eye close.

**Comment by hellotaran** [comment]
@filmaj Not yet. As @gahag said tracking number would be awesome if possible.

**Comment by DanielRuf** [comment]
It's normal outside of US that it takes a "bit" longer. For Germany I had 4 - 6 weeks until deliveries arrived.

**Comment by hellotaran** [comment]
@DanielRuf Mine is USA. Just in case...

**Comment by DanielRuf** [comment]
Be patient, I guess you had holidays too. ;-)

**Comment by andrey-legayev** [comment]
I still didn't receive t-shirt. Is it expected delivery time or it's lost already on the way?

**Comment by haktober** [comment]
Also haven't.

**Comment by drpayyne** [comment]
I just received mine yesterday, in India. Also, I had to send some verification for it to clear airport customs. So maybe check that too.

**Comment by gahag** [comment]
Also haven't.

**Comment by hostep** [comment]
I've got mine 3 days ago (Belgium), I like the color, thanks btw!

**Comment by hellotaran** [comment]
Still waiting. @filmaj  You can bring in mine to Imagine if does not get deliver before :)

**Comment by DanielRuf** [comment]
The tshirts were already sent so it would still arrive ;-)

**Comment by filmaj** [comment]
Yeah, sorry y'all, sucks that it's taking this long but we sent them all out around mid-December. It wouldn't surprise me if it would take up to a couple of months. Make sure you check your snail mail and look for any customs forms or notifications.

A couple of you received customs notifications that asked for further details (commercial invoice) which we can provide if that is helpful - if you need that, fire us an email at engcom@adobe.com.

**Comment by DanielRuf** [comment]
So far it didn't arrive yet here.
When did the others get it?

**Comment by krzksz** [comment]
I got mine this week (Poland).

pt., 7 lut 2020, 07:06 użytkownik Daniel Ruf <notifications@github.com>
napisał:

**Comment by mahesh-rajawat** [comment]
I've got mine 2 days ago (India)

**Comment by Bartlomiejsz** [comment]
There's no rule I see since I also in Poland like @krzksz received mine over two weeks ago

**Comment by edenduong** [comment]
![image](https://user-images.githubusercontent.com/8234209/74008093-9faad200-49b2-11ea-8bce-077eb62ac255.png)

I got it at 23-12-2019 (very fast) :)  (I come from Vietnam)

**Comment by carusogabriel** [comment]
I've received mine last week in Amsterdam, NL

**Comment by medusalix** [comment]
@DanielRuf You're not the only one from Germany who hasn't received their shirt yet ✋.

**Comment by cedarvinda** [comment]
@filmaj can you send me my invoice please? I had drop a mail to you as well its now approx more than 7-8 days.
**1.** Air Waybill No is. 777566984667
**2.** Name : Arvinda kumar
**3.** GitHub.com username : cedarvinda
**4.** T-shirt size : large
**5.** full shipping address : CEDCOSS Technologies Private Limited , 3/460, Opp to Nehru Enclave, Vishwas Khand, Lucknow, Uttar Pradesh 226010
**6.** Contact number : +91 8887684411

**Comment by andrey-legayev** [comment]
I've received t-shirt several days ago. Ukraine.
Thanks!

**Comment by DanielRuf** [comment]
Mine arrived today attached with the commercial invoice. It was sent from Austin, Texas on 6th of February. So it seems it waited there in the USA for a few weeks.

**Comment by gahag** [comment]
Got mine this week too.

**Comment by revanth0212** [comment]
Received mine. Thank you 👍

**Comment by medusalix** [comment]
Mine arrived today too 😃.

**Comment by SebastianKlett** [comment]
Finally arrived in Australia as well :-) Thanks

**Comment by milindsingh** [comment]
when will 2020 fest start?
